# Auto-labeling configuration for pull requests
# Labels are applied based on which files are changed

# Backend changes
backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**/*'

# Frontend changes
frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.md'
      - 'docs/**/*'

# CI/CD changes
ci-cd:
  - changed-files:
    - any-glob-to-any-file: 
      - '.github/**/*'
      - 'docker-compose*.yml'
      - '**/Dockerfile*'
      - 'nginx.conf'

# Database changes
database:
  - changed-files:
    - any-glob-to-any-file: 
      - 'backend/prisma/**/*'
      - '**/migrations/**/*'

# Tests
tests:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/__tests__/**/*'
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/*.properties.test.ts'

# Configuration
config:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.config.js'
      - '**/*.config.ts'
      - '**/tsconfig*.json'
      - '**/.eslintrc*'
      - '**/.prettierrc*'
      - '.env.example'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/package.json'
      - '**/package-lock.json'
